### PR TITLE
pass $self and args to ajax route handlers (#7)

### LINKED ISSUE #7: $self is not passed to ajax route handlers
It is not possible to get `$self` in `ajax` route handlers, because there are no arguments passed to the handler. The following code produces an empty array ref `[]` in the Dancer log.

```perl
use Dancer2;
use Dancer2::Plugin::Ajax;

ajax '/' => sub {
  use Data::Printer;
  p @_;
};

dance;

__END__
curl --header 'X-Requested-With: XMLHttpRequest' localhost:3000/
```
If the `ajax` is replaced with `get`, `@_` will contain `$self` and `@args`.

**This behaviour should be consistent**, and `ajax` route handlers should provide `$self` and `@args`. 

It needs to be added in https://github.com/PerlDancer/Dancer2-Plugin-Ajax/blob/master/lib/Dancer2/Plugin/Ajax.pm#L46.

This was discovered in https://stackoverflow.com/q/53006485/1331451.

### PR DESCRIPTION
**Pull request by simbabque**
Fixes #7

### CODE REVIEW

**Comment by cromedome** [comment]
Thanks @simbabque! :+1:

**Review by yanick — CHANGES_REQUESTED** [review]
Mention that `$app` argument in the POD documentation?

**Comment by simbabque** [comment]
@yanick please see my update. I agree that should have been in, it's definitely better if it is documented.

**Comment by yanick** [comment]
Beautiful! I heartily :+1: it. :-)

**Review by yanick — APPROVED** [review]

**Pull request merged**
